---
- name: Run Flyway
  docker_container:
    name: flyway
    image: dhoer/flyway:4.1.2
    volumes:
      - "/path/to/flyway/sql:/flyway/sql"
    command: "migrate -url={{ flyway_db_url }} -user={{ flyway_db_user }} -password={{ flyway_db_password }}"  
    recreate: yes
    detach: False
