---
- name: Run Flyway
  docker_container:
    name: flyway
    image: boxfuse/flyway:5.1-alpine
    volumes:
      - "/path/to/flyway/sql:/flyway/sql"
    command: "migrate -url={{ flyway_db_url }} -user={{ flyway_db_user }} -password={{ flyway_db_password }} -schemas={{ flyway_db_schemas }}"
    recreate: yes
    detach: False
